image:
  repository: ghcr.io/priyanka1997devaraj/devops-task-manager
  tag: "5bed8054162cb595123fc828197faff308e6404e"
  pullPolicy: Always

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
