image:
  repository: ghcr.io/priyanka1997devaraj/devops-task-manager
  tag: "ab354c2405abcaf9ddd198c34c5850158f979d82"
  pullPolicy: Always

replicaCount: 2

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
